### ISSUE TITLE
.format(new Date()) doesn't work.

### ISSUE THREAD

**Issue by pcdummy** [johnspackman/qxcompiler#11]
After looking closely to my [qooxdoo-tweets-tutorial](https://pcdummy.github.io/qooxdoo-tweets-tutorial/) build with QxCompiler i found out that dates don't "format" correctly.

This code doesn't work as accepted:
```javascript
qx.util.format.DateFormat.getDateTimeInstance().format(new Date());
```

**Comment by johnspackman** [comment]
fixed in latest release
