### ISSUE TITLE
Latest Master of Qx doesn't work with this

### ISSUE THREAD

**Issue by pcdummy** [johnspackman/qxcompiler#12]
It compiles fine but in the Browser i get errors:

![qx-master-qxcompiler-error](https://cloud.githubusercontent.com/assets/358074/18036062/9786430a-6d62-11e6-8e75-aaf491626a59.png)

**Comment by johnspackman** [comment]
Do you have an app I can reproduce this with?

**Comment by pcdummy** [comment]
Yes: https://github.com/pcdummy/qooxdoo-tweets-tutorial/

**Comment by johnspackman** [comment]
fixed in latest release
